[package]
name = "onlinelimiter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
steam-api = "0.4.1"
anyhow = "1.0.79"
chrono = "0.4.33"
